all:
	gcc my_tcpserver.c -o my_tcpserver
	gcc my_tcpclient.c -o my_tcpclient
	gcc my_udpserver.c -o my_udpserver
	gcc my_udpclient.c -o my_udpclient

clean:
	rm my_tcpclient my_tcpserver my_udpclient my_udpserver
