./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
./dnsc < input.txt &
